name: JD_Actions
on:
  schedule:
    - cron: 5 */2 * * *
  workflow_dispatch:
  watch:
    types: started
jobs:
  build:
    runs-on: Ubuntu-20.04  
    steps:
    - name: set_time
      run: |
        cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        date
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        sudo npm install -g typescript
        sudo apt-get install wget
    - name: down
      run: |
        echo "========= 开始清空脚本 ========="
        shopt -s extglob
        rm -rf !(README.md|package.json)
        shopt -u extglob
        echo "========= 开始下载小小的脚本及依赖 ========="
        git clone -b jd_scripts https://github.com/Aaron-lv/sync.git ./Aaron
        rm ./Aaron/package.json
        cp -rf ./Aaron/* ./
        rm -rf ./Aaron
        echo "========= 开始下载smiek2221的脚本 ========="
        wget -N https://raw.githubusercontent.com/smiek2221/scripts/master/gua_MMdou.js
        wget -N https://raw.githubusercontent.com/smiek2221/scripts/master/gua_wealth_island.js
        wget -N https://raw.githubusercontent.com/smiek2221/scripts/master/gua_wealth_island_help.js
        wget -N https://raw.githubusercontent.com/smiek2221/scripts/master/gua_city.js
        echo "========= 开始下载JDHelloWorld的脚本 ========="
        git clone https://github.com/JDHelloWorld/jd_scripts.git ./JDHelloWorld
        echo "========= 开始复制依赖 ========="
        cp -f ./JDHelloWorld/*ShareCodes.js ./
        cp -rf ./JDHelloWorld/{jd_plantBean.js,jd_fruit.js,jd_pet.js,jd_dreamFactory.js,jd_jdfactory.js,jd_sgmh.js,jd_reward.js,jd_redPacket.js} ./
        echo "========= 开始转换JDHelloWorld的ts脚本 ========="
        cd ./JDHelloWorld
        rm -rf ./backUp
        rm `ls *.js|egrep -v sendNotify.js`
        sed -i 's#setCookie: string\[\]#setCookie: any#g' ./jd_qq_pasture.ts
        sed -i 's#appId = 10032#appId: any = 10032#g' ./TS_USER_AGENTS.ts
        sudo npm install
        tsc
        sed -i '/except.includes(encodeURIComponent(UserName)/,+3d' *.js
        sed -i 's/sendNotify_1.sendNotify/notify.sendNotify/g' *.js
        echo "========= 开始复制JDHelloWorld的脚本 ========="
        cd ..
        awk 'BEGIN { cmd="cp -ri ./JDHelloWorld/utils ./"; print "n" |cmd; }'
        mv ./JDHelloWorld/jd_jxmc.js ./JDHelloWorld/jd_jxmch.js
        mv ./JDHelloWorld/jd_cfd.js ./JDHelloWorld/jd_cfdh.js
        awk 'BEGIN { cmd="cp -i ./JDHelloWorld/*_*.js ./"; print "n" |cmd; }'
        rm -rf ./JDHelloWorld
    - name: 'Commit Files'
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -am "$(date +%Y%m%d-%H:%M)"
    - name: Push Dust
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        branch: master
